# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/openjdk:8-jdk

  working_directory: ~/jmxfetch

  environment:
    MAVEN_OPTS: -Xmx3200m

cache_keys: &cache_keys
  # Reset the cache approx every release
  keys:
    - jmxfetch-{{ checksum "pom.xml" }}-{{ .Branch }}-{{ .Revision }}
    - jmxfetch-{{ checksum "pom.xml" }}-{{ .Branch }}
    - jmxfetch-{{ checksum "pom.xml" }}

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          <<: *cache_keys

      - run: mvn install

      - save_cache:
          paths:
            - ~/.m2
          key: jmxfetch-{{ checksum "pom.xml" }}-{{ .Branch }}-{{ .Revision }}

      - store_test_results:
          path: ./target/surefire-reports/

      - persist_to_workspace:
          root: .
          paths:
            - target

  build_single_assembly:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          <<: *cache_keys

      - run: mvn clean compile assembly:single

      - save_cache:
          paths:
            - ~/.m2
          key: jmxfetch-{{ checksum "pom.xml" }}-{{ .Branch }}-{{ .Revision }}

      - store_test_results:
          path: ./target/surefire-reports/

      - persist_to_workspace:
          root: .
          paths:
            - target

  deploy_maven:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          <<: *cache_keys

      - attach_workspace:
          at: .

      - run: mvn validate jar:jar deploy:deploy -e -X --settings ./settings.xml


  deploy_bintray:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          <<: *cache_keys

      - attach_workspace:
          at: .

      - run: find ./

workflows:
  version: 2
  build_test_deploy_single_assembly:
    jobs:
    - build_single_assembly:
        filters:
          tags:
            only: /.*/
    - deploy_bintray:
        requires:
          - build_single_assembly
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^\d+\.\d+\.\d+/
  build_test_deploy_maven:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - deploy_maven:
        requires:
          - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^\d+\.\d+\.\d+/
