# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

defaults: &defaults
  working_directory: ~/jmxfetch

  environment:
    MAVEN_OPTS: -Xmx3200m

cache_keys: &cache_keys
  # Reset the cache approx every release
  keys:
    - jmxfetch-{{ checksum "pom.xml" }}-{{ .Branch }}-{{ .Revision }}
    - jmxfetch-{{ checksum "pom.xml" }}-{{ .Branch }}
    - jmxfetch-{{ checksum "pom.xml" }}

build_steps: &build_steps
  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        <<: *cache_keys

    - run: mvn install

    - save_cache:
        paths:
          - ~/.m2
        key: jmxfetch-{{ checksum "pom.xml" }}-{{ .Branch }}-{{ .Revision }}

    - store_test_results:
        path: ./target/surefire-reports/

    - persist_to_workspace:
        root: .
        paths:
          - target

jobs:
  build8:
    docker:
      - image: circleci/openjdk:8-jdk
    <<: *defaults

    <<: *build_steps

  build9:
    docker:
      - image: circleci/openjdk:9-jdk
    <<: *defaults

    <<: *build_steps

  build11:
    docker:
      - image: circleci/openjdk:11-jdk
    <<: *defaults

    <<: *build_steps

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk

    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          <<: *cache_keys

      - attach_workspace:
          at: .

      - run: mvn validate jar:jar source:jar javadoc:jar assembly:single deploy:deploy -e --settings ./settings.xml


filters: &workflow_build_filters
  tags:
    only: /.*/

workflows:
  version: 2
  build_test_deploy:
    jobs:
    - build8:
      <<: *workflow_build_filters
    - build9:
      <<: *workflow_build_filters
    - build11:
      <<: *workflow_build_filters
    - deploy:
        requires:
          - build8
          - build9
          - build11
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^\d+\.\d+\.\d+/
